Repository decide-moltres/decide-censo, pull requests merged in 2020-01, with the labels that each got.

#25 Develop
  decide/census/models.py
  decide/census/test_model.py
  decide/census/tests.py
  decide/store/tests.py
  decide/voting/tests.py
Labels: Prioridad alta, Tipo error: prueba o test

#35 Develop
  .travis.yml
  decide/base/templates/base.html
  decide/base/templates/index.html
  decide/base/urls.py
  decide/base/views.py
  decide/census/admin.py
  decide/census/models.py
  decide/census/static/census/style.css
  decide/census/templates/census_history.html
  decide/census/templates/delete_census.html
  decide/census/templates/edit_census.html
  decide/census/templates/list_census.html
  decide/census/templates/view_voters.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/decide/urls.py
  decide/local_settings.example.py
  decide/locale/ca/LC_MESSAGES/django.po
  decide/locale/en_US/LC_MESSAGES/django.po
  decide/locale/es/LC_MESSAGES/django.po
  decide/locale/eu/LC_MESSAGES/django.po
  decide/locale/gl/LC_MESSAGES/django.po
  requirements.txt
Labels: Prioridad alta, enhancement

#34 Fucionalidad corrector
  decide/census/admin.py
Labels: Tipo actividad: mejora
